### ISSUE TITLE
Reading of writeprints_limited_norm.xml prints "failed!" four times

### ISSUE THREAD

**Issue by hartwork** [psal/JStylo-Anonymouth#6]
```
$ java [..] edu.drexel.psal.GUI.JSANGUIChooser
[..]
23-18-58: Reading CumulativeFeatureDriver from [..]/./jsan_resources/feature_sets/writeprints_limited_norm.xml
failed!
failed!
failed!
failed!
[..]
```

**Comment by travis-crow** [comment]
This is a known issue with the old version of the XML file for the
writeprints_limited_normalized feature set. Some of the features reference
drivers which have not yet been developed. The newer version of JStylo
notifies the user of which feature drivers fail, and also fixes one of the
XML entries, which was simply mislabeled. The fix was also supposed to stop
them from trying to run without being set, but I just tried to verify and
noted that it does not. However, identifying and removing the offending
features should prevent the issue. I'll look into preventing them from
crashing the evaluation (without needing the user to manually remove them).
The README has just recently been updated to reflect the fact that JStylo
and Anonymouth have moved to new repositories. Anonymouth has not yet
completed its transition, but once it has, it will be located at (
https://github.com/psal/anonymouth ). JStylo has moved to an alternate
repository located at ( https://github.com/psal/jstylo ) and is several
updates ahead in the new repository.

Thanks,
--Travis

On Wed, Jun 26, 2013 at 5:22 PM, Sebastian Pipping <notifications@github.com

**Comment by travis-crow** [comment]
Just in case anyone wanted to read another in what is sure to be a long
line of fc papers, I've attached the current version of the short paper/in
progress submission on the variable length stylo stuff. If any of you have
the chance to look it over and comment, I'd appreciate it.

Thanks,
-Travis

**Comment by hartwork** [comment]
No interest apparently, closing to keep listing https://github.com/issues clean…
